### ISSUE TITLE
There are some issues in project?

### ISSUE THREAD

**Issue by keviny1981** [e-hat/efgl#1]
Hello,

I've cloned and compiled your project.
I didn't change anything but I'm getting following errors
- SandboxApplication shows nothing, everything has loaded up properly but don't know why it shows black, seems like something is clearing sphere immediately?
> I don't see any error from console except some warnings, I know they are not in use in shader (pbr_demo.glsl)
> Warning: Uniform light.constant doesn't exist.
> Warning: Uniform light.linear doesn't exist.
> Warning: Uniform light.quadratic doesn't exist.
> Warning: Uniform light.radius doesn't exist.
- ManyLightsDemo throws an error always right after the meshes gets loaded
> [OpenGL Error] (1282): glUseProgram(m_RendererID) efgl/src/ComputeShader.cpp:119
> Error: INVALID_OPERATION (1282)

Can you please take a look and help me out to make it work? :)

**Comment by efthatfield** [comment]
Thanks for letting me know. I'll check this out.

**Comment by efthatfield** [comment]
Sorry, haven't worked on this project for a long time. https://github.com/e-hat/efgl/commit/e71d55ac7b101ccf645ded083741f19bcb3d394a fixes this for me on linux.
